### ISSUE TITLE
revdep errors with gdtools update

### ISSUE THREAD

**Issue by davidgohel** [lionel-/vdiffr#23]
Hi 

I have to make an update to gdtools because of a new version of fontconfig that slightly changes computed extends:

https://cran.r-project.org/web/checks/check_results_gdtools.html

It's almost done but I have 2 errors left when *revdep_checking*:

    testthat results ================================================================
    OK: 22 SKIPPED: 0 FAILED: 2
    1. Failure: Doppelgangers pass (@test-expectations.R#24) 
    2. Failure: ggtitle is set correctly (@test-ggplot.R#8) 

I don't really understand the script, is it caused by gdtools? I think it is because font metrics changed on cran platforms that are using the new fontconfig version. If yes, would you be ok to resubmit after new gdtools submission? I think it implies to update expected results in unit tests.

Thanks,
David

**Comment by lionel-** [comment]
The text extents have changed because of FreeType 2.8.0. I'm preparing a release where tests skip if FreeType doesn't match: https://github.com/lionel-/vdiffr/pull/22

**Comment by davidgohel** [comment]
OK, sorry

I will submit the updated version now then.

**Comment by lionel-** [comment]
sounds good, thanks!
