### ISSUE TITLE
vdiffr won't run when system libfreetype is too old

### ISSUE THREAD

**Issue by clauswilke** [lionel-/vdiffr#39]
Even though vdiffr now uses a statically linked libfreetype, it still tests for the version of the system library. As a consequence, if that version is too old, vdiffr won't run. The relevant lines in the code are here:
https://github.com/lionel-/vdiffr/blob/43fbfce764b2c99960614ebc7472dca190fda3e6/R/testthat-ui.R#L53-L57

See also: https://github.com/tidyverse/ggplot2/issues/2838

**Comment by lionel-** [comment]
Good catch thanks! Not sure this will fix the Travis issue though.

**Comment by lionel-** [comment]
> Not sure this will fix the Travis issue though.

oops just saw your link to the logs. That's strange, it seems like current Travis has an older FreeType version than in the past.

**Comment by lionel-** [comment]
This fixes vdiffr Travis build 👍
