### ISSUE TITLE
Support for viewing of textual diffs in shiny app 

### ISSUE THREAD

**Issue by cpsievert** [lionel-/vdiffr#44]
It seems the current suggestion is to view textual diffs via git. There are at least two problems there:

1. Hard for beginners to use or be aware of.
2. Git diffs aren't very readable when viewing single line svg files
3. Sometimes you may want to view the diff during validation. 

It seems like it'd be a big improvement to put something like `diffObj::diffChr()` in a new tabset of the shiny app.

**Comment by lionel-** [comment]
👍
