### ISSUE TITLE
Log of R CMD check failures is not generated

### ISSUE THREAD

**Issue by zlskidmore** [lionel-/vdiffr#52]
Hi,

I've noticed that when I run vdiffr::manage_cases() I can validate/verify my test cases are passing. However as soon as I run devtools::check() I get failures for these visual test cases. I'm not sure what would be be causing this or how to debug it. Any insights would be appreciated!

I only have one version of freeType installed on my system and even if 2 versions were being used from my understanding that would cause the test to be skipped and not fail correct?

**Comment by lionel-** [comment]
Hello, are you using the development version?

**Comment by zlskidmore** [comment]
I'm on the latest cran release 0.2.3, I'll update to the dev version and see what happens

**Comment by lionel-** [comment]
You'll need to regenerate all figures. On the upside, the new generation approach should finally be stable.

**Comment by zlskidmore** [comment]
hmm, still seeing the same issue after updating to the dev version. any ideas?

**Comment by lionel-** [comment]
is there anything that could cause undeterministic generation? Do you need to `set.seed()` before tests for example? (though in the latter case it should fail with `devtools::test()` as well I think)

**Comment by lionel-** [comment]
Also you should have a `vdiffr.Rout.fail` file generated in the temporary directory where R CMD check is run. Diffing it with your recorded SVGs could help you find what is causing trouble.

**Comment by lionel-** [comment]
That does look weird. It looks like the grid.draw will be called before the svglite context is set. What happens if you try this instead, to ensure grid.draw is called at the right time:

```r
vdiffr::expect_doppelganger("Lolliplot Density Plot", function() grid::grid.draw(buildDensityPlot.out))
```

**Comment by zlskidmore** [comment]
still the same issue:

I also tried loading the `ggplotify` library and doing something like this

```R
test_that("buildDensityPlot constructs the expected plot", {

    skip_on_bioc()
    skip_if_not(biomart_success, "mart recieved try-error")

    buildDensityPlot.out <- buildDensityPlot(LolliplotData.mode1.out, plotALayers=NULL, verbose=FALSE)
    
    tmp <- as.ggplot(buildDensityPlot.out)

    vdiffr::expect_doppelganger("Lolliplot Density Plot", print(tmp))
    
})
```

But get the error `svglite only supports one page` I think `ggplotGrob` might be introducing a blank page from what i've read here https://github.com/wilkelab/cowplot/issues/24 but not sure how to work around that yet

**Comment by lionel-** [comment]
The `print()` call must be guarded by a function: `function() print(tmp)`.

**Comment by lionel-** [comment]
or you can pass `tmp` directly if it's a ggplot2 object.

**Comment by zlskidmore** [comment]
Ah, okay, that allowed things to proceed, still see the same issue as before though. Is there a way to dig into the code during R CMD CHECK?

**Comment by lionel-** [comment]
I will fix the generation of logs in the CMD check directory once I resume work on vdiffr. Priorities right now are to release new versions of purrr and tidyselect however, so it could be a little while :/

**Comment by lionel-** [comment]
The generation of the log file should be fixed. I have also added a section in the README about debugging unexpected failures: https://github.com/lionel-/vdiffr#debugging
